name: app_mapeo
description: "Aplicación de mapeo agrícola con GPS"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  dropdown_search: ^5.0.6
  collection: ^1.18.0
  flutter_slidable: ^3.0.1
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  multi_select_flutter: ^4.1.3
  provider: ^6.0.5
  crypto: ^3.0.3
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/lh.jpg
    - assets/images/fondo.jpg
